# Generated by Django 6.1 on 2026-08-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller_phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='seller_whatsapp',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
