# Generated by Django 6.1 on 2026-08-12 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_seller_phone_car_seller_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('kilometers', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seller_whatsapp',
        ),
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='car',
            name='seller_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='cars.car')),
            ],
        ),
    ]
